### ISSUE TITLE
Fix test #77

### ISSUE THREAD

**Issue by mattrpav** [highsource/jaxb-tools#215]
Test 77 does not pass currently. This needs to be looked into and fixed.

**Comment by laurentschoelens** [comment]
Hi @mattrpav :
Found a way to fix this issue and issue #244 without breaking anything and with previous config of this issue in maven pom (like it was in 0.14.0 release where it last passed)
Build OK with jdk8 / jdk11 / jdk17

Problem is xjc introduced (like mentioned in #244) default empty systemId (where it was null before - because no more accepted as valid systemId in jdk9+) so the check in ReResolvingEntityResolverWrapper consisting of overiding systemId with resolved one if initial systemId is null is no more valid.
Will commit this after repos merge successful 😄

**Comment by mattrpav** [comment]
Fixed in v2.0.4
