### ISSUE TITLE
JAXB Plugin Roadmp

### ISSUE THREAD

**Issue by mattrpav** [highsource/jaxb-tools#260]
Github Project milestones are updated and reflect the current roadmap plan:

Revised roadmap:

1. 0.15.3 - remove legacy 2.x modules, update to JDK 8
2. 2.0.0-SNAPSHOT - Rename groupId, maven artifactId to org.jvnet.jaxb / jaxb-maven-plugin
3. 3.0.0-SNAPSHOT - JDK 8 + Jakarta jaxb 3
4. 4.0.0-SNAPSHOT - JDK 11 + Jakarta jaxb 4 and jakarta namespace

**Comment by tgillain** [comment]
Hello,

We are currently in the process of migrating from Springboot 2.7.x to 3.0.x which only supports the Jakarta packages. Do you have an idea when the 3.0.0 and 4.0.0 version of the plugin could be available ?

Brs.

**Comment by laurentschoelens** [comment]
@tgillain : current work is still in progress - I've just provided the PR to get the 3 mainstreams projects into this one (jaxb-tools) since we can't migrate to jakarta without migrating the 3 projects at the same time and they have inter-dependencies on build.
When this PR will be approved, we still need to do some work to fix some dependencies issues and then provide a v3 plugin version for jakarta migration. This will come very soon so stay tuned :)

**Comment by tgillain** [comment]
@laurentschoelens That looks promising :) 
Tell me if I can be of any help.

**Comment by laurentschoelens** [comment]
If you see any issue that you might think would need to be fixed before jakarta migration, tell us, and if it's worth working on it, try to provide a PR for it using CONTRIBUTION guide

**Comment by laurentschoelens** [comment]
We are currently and activly working on this
Jakarta jaxb3 support should come by the end of the month in my opinion
Stay tuned

**Comment by mattrpav** [comment]
release v4.0.0 underway
