### ISSUE TITLE
[JAXB-1045] "Item" is already defined error with catalogs, bindings and mixed absolute and relative URLs

### ISSUE THREAD

**Issue by bracouda** [highsource/jaxb-tools#47]
Hello,

I have a question about catalog and import. 
In the sample project ( org.jvnet.jaxb2.maven2:maven-jaxb2-plugin-sample-catalog-maven)
there is this part in project-pom.xml

``` xml
<configuration>
    <catalog>src/main/resources/catalog.cat</catalog>
    <schemaIncludes>
        <schemaInclude>schema_b.xsd</schemaInclude>
    </schemaIncludes>
</configuration>
```

but if we do something like that:

``` xml
<configuration>
    <catalog>src/main/resources/catalog.cat</catalog>
    <schemaIncludes>
        <schemaInclude>*.xsd</schemaInclude>
    </schemaIncludes>
</configuration>
```

you will have this error

``` java
[INFO] Sources are not up-to-date, XJC will be executed.
[ERROR] Error while parsing schema(s).Location [ http://example.org/schemas/schema_a.xsd http://example.org/A{8,13}].
org.xml.sax.SAXParseExceptionpublicId: http://example.org/A; systemId: http://example.org/schemas/schema_a.xsd; lineNumber: 8; columnNumber: 13; 'SomeComplexType' is already defined
    at com.sun.xml.xsom.impl.parser.ParserContext$1.reportError(ParserContext.java:180)
    at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.reportError(NGCCRuntimeEx.java:175)
    at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.reportError(NGCCRuntimeEx.java:178)
    at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.checkDoubleDefError(NGCCRuntimeEx.java:150)
    at com.sun.xml.xsom.impl.parser.state.Schema.action5(Schema.java:127)
    at com.sun.xml.xsom.impl.parser.state.Schema.onChildCompleted(Schema.java:1286)
...
[ERROR] Error while parsing schema(s).Location [ file:/C:/Users/toto/git/maven-jaxb2-plugin/samples/catalog/src/main/resources/schema_a.xsd{6,42}].
org.xml.sax.SAXParseException; systemId: file:/C:/Users/toto/git/maven-jaxb2-plugin/samples/catalog/src/main/resources/schema_a.xsd; lineNumber: 6; columnNumber: 42; (related to above error) the first definition appears here
    at com.sun.xml.xsom.impl.parser.ParserContext$1.reportError(ParserContext.java:180)
    at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.reportError(NGCCRuntimeEx.java:175)
    at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.checkDoubleDefError(NGCCRuntimeEx.java:151)
    at com.sun.xml.xsom.impl.parser.state.Schema.action5(Schema.java:127)
...
```

and in case if i change in the xsd the shemaLocation

``` xml
    <xs:import namespace="http://example.org/A" schemaLocation="http://example.org/schemas/schema_a.xsd"/>
```

to

``` xml
    <xs:import namespace="http://example.org/A" schemaLocation="./schema_a.xsd"/>
```

(still have *.xsd in schemaInclude)
It's working.

So i guess the catalog rewrite doesn't work very well ?
Do you think it could be fixed in the plugin ?

**Comment by highsource** [comment]
Catalogs are very tricky. :)

This is a known bug in XJC:

https://java.net/jira/browse/JAXB-1045

The problem is that XJC uses original URLs to identify resources, so a local file and a global URL are different URLs for it, even if the global one gets resolved to the same local file.

I even tried provided a patch for XJC (https://github.com/gf-metro/jaxb/pull/7), but it did not work in the `-nv` mode. And JAXB people are quite reluctant accepting PRs anyway. So I think I'll have to provide a patched version of XJC at the end, see #highsource/exjc/2.

I'll leave this issue open until it is really fixed, but will rename it.

**Comment by bracouda** [comment]
Thank you for your answer.

In final, for my project i found a workaround.
I don't use catalog but instead i use relative link in my xsd
and this maven plugin to replace path

```xml
<dependency>
  <groupId>com.google.code.maven-replacer-plugin</groupId>
  <artifactId>replacer</artifactId>
  <version>${replacer.version}</version>
</dependency>
```

**Comment by highsource** [comment]
Yes, sure, the workaround is possible. I sometimes patch schemas prior to compilation.

Bu its must really work at the end. This is clearly a bug in XJC.

**Comment by allqvist** [comment]
The workaround we use is to always use the full ("public") schemaLocation, even if the schema resides in the same "schema module". To come around the trivial problem of double compilation, we move the (locally) imported schemas to a "side catalog" ("src/main/xsd-1" instead of "src/main/xsd"), and use the catalog to map the full schemaLocation to that directory (rewrite to "src/main/xsd-1").

The effect is that the imported schemas are excluded from being sent directly to xjc, but they're indirectly compiled by being imported.

The important thing is that this allows us to Always use the same schemaLocation when doing imports, regardless of whether the imported schema is local or remote. This makes the xjc command (and, for that matter, the wsimport command) much happier!

This simple procedure could be done by your plugin - having an (optional?) pass that excludes any imported schemas from the set of schemas sent directly to xjc.

**Comment by highsource** [comment]
@allqvist Hm, I think this goes way too far for a workaround. Analyzing import structure of schemas, moving files around to overcome a bug in XJC... I really don't think this should be done this way. I'd rather fork/patch XJC instead, would be probably less work.

**Comment by allqvist** [comment]
I guess you're right. On second thought (btw), we revised our strategy to use (explicit) schema excludes in the pom file. So, here it goes:

1) Always use the same "global schema location", even for that modules' "local" schemas

2) In the catalog, map that "global schema location" to "./"

3) For all "local import" schemas, do a schemaExcludes/exclude

Actually, it looks pretty OK now. 

Maybe, possibly, in the future, step 3 could be automated, i.e. if the resolved name ends up in the schemaDirectory, it could automatically be excluded. 
On the other hand, if you know what you're looking for, it's shows up in the error logs.

/Regards

**Comment by kattn** [comment]
Is there possible to get a more step by step workaround untill this is fixed? I'm having truble understanding what is meant by "global schema location" and local schemas etc.

**Comment by tomtobin** [comment]
@highsource - do you have a copy of that patch referenced above, it seems to have been removed from github?

**Comment by highsource** [comment]
@tomtobin No, I don't have it anymore. Where's JAXB gone from GitHub?
I think I would be able to restore it, as far as I remember it was no big deal.

**Comment by highsource** [comment]
Relevant: https://github.com/javaee/jaxb-v2/issues/1045

**Comment by highsource** [comment]
https://github.com/eclipse-ee4j/jaxb-ri/issues/1045
