### ISSUE TITLE
Problem with using jaxb2 inheritance plugin when using jaxws binding.

### ISSUE THREAD

**Issue by Blomex** [highsource/jaxb-tools#471]
Recently I've encountered the issue while to trying to generate classes from wsdl, but with custom interface implementation.
I described it in details on stack overflow: 
https://stackoverflow.com/questions/77726698/using-jaxws-plugin-to-generate-java-classes-from-wsdl-that-will-implement-common/77730456?noredirect=1#comment137040172_77730456

Here is the repo with MRE:
https://github.com/Blomex/jaxws-generating-classe-mre

to generate code, one can simply use 
```
mvn -U clean compile
```
binding is working (we can see BookType class is generated with name 'Book') but the inheritance part is not taken into account.
While when uncommenting xs:annotation inside wsdl, it will generate the files correctly, I'm trying to understand, why it doesn't generate it by binding, as it should be enough.

**Comment by laurentschoelens** [comment]
Thanks for the issue @Blomex  
I'll try investigate soon so, if bug exists, we could fix it in the next release (and backport in 2.x branch)

**Comment by laurentschoelens** [comment]
After debugging the `wsimport`, it seems that the `extensionBindingPrefixes` attribute you can set in `jaxb:bindings` is not taken into account when defined in `jaxws:bindings` and it seems to be by design according the `jaxb:bindings`' XSD

> A binding compiler only processes this attribute when it occurs on an instance of xs:schema element. The value of this attribute is a whitespace-separated list of namespace prefixes. The namespace bound to each of the prefixes is designated as a customization declaration namespace.

If you want to use bindings to customize the output with `extensionBindingPrefixes` plugins, you need to externalize the XSD into is own file and then use the standard `jaxb:bindings` process.

The section of `wsdl:types` should look like the following :

```xml
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.cleverbuilder.com/BookService/" schemaLocation="my_xsd.xsd" />
        </xsd:schema>
    </wsdl:types>
```

And the `my_xsd.xsd` file would contain the schema definition elements.

This also explains why defining it inline the WSDL makes it work (since the `extensionBindingPrefixes` has been defined on `xs:schema`)
