### ISSUE TITLE
-Xfluent-builder is not supported

### ISSUE THREAD

**Issue by Vishal-Joshi** [highsource/jaxb-tools#508]
I used to use `org.jvnet.jaxb2.maven2:maven-jaxb2-plugin v0.14.0` to create builders in generated classes using `-Xfluent-builder`

However, when I switch to `org.jvnet.jaxb:jaxb-maven-plugin v2.0.9` the argument `-Xfluent-builder` is not supported. 
I tried using the `-Xfluent-api` as mentioned here https://github.com/highsource/jaxb-tools/wiki/JAXB2-Fluent-API-Plugin
but that generates the `with*` methods and not Builder in the generated class.

Are builders not supported anymore?

**Comment by laurentschoelens** [comment]
Could you share a code sample of expected ?

I've created test project (that I'll push in next v4) and generated code is like :

```java
public Address withStreet(String value) {
  setStreet(value);
  return this;
}

public Address withNumber(int value) {
  setNumber(value);
  return this;
}
```

So you can chain code like 
```java
Address a = new Address();
a.withStreet("MyStreet").withNumber(10);
```

**Comment by laurentschoelens** [comment]
Moreover, could you tell me from where the `-Xfluent-builder` arg came from ? Which xjc plugin ? Thanks

**Comment by Vishal-Joshi** [comment]
Hi @laurentschoelens 
`-Xfluent-builder` from `org.jvnet.jaxb2.maven2:maven-jaxb2-plugin v0.14.0` would created a builder method in the unmarshalled class from xml. It is the implementation of builder pattern

A sample class would invocation would look like,

```
FactSet factSet = FactSet.builder()
                    .withFact(builder().withType("type1").build(), builder().withType("type2").build())
                    .build();
```
where FactSet was an unmarshalled class from a given xml. The `builder()` and `build()` were added by the jaxb plugin's xjc implantation

**Comment by laurentschoelens** [comment]
Thanks but the `Xfluent-builder` does not came from here. Could you share sample `pom.xml` config ?

**Comment by laurentschoelens** [comment]
One option I'm thinking of is that the xjc plugin responsible of handling `Xfluent-builder` is defined in parent `pom.xml` in plugin / pluginManagament configuration with the older coordinates (`org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0`) but since you move to the newest version of jaxb-tools for jaxb2 (2.0.9), the configuration is no more inherited from parent.

I'm also pretty sure you are using the following library : https://github.com/mklemm/jaxb2-rich-contract-plugin which refers to same configuration as yours.

I'll try to contact or propore PR to update documentation according to latest version of jaxb-tools.

**Comment by laurentschoelens** [comment]
Feel free to reopen issue if you still have problems, providing more details. Thanks
FI : 4.0.0 of `net.codesup.util:jaxb2-rich-contract-plugin` has just been released, with support of JAXB4
It should take a few hours before getting to maven-central

**Comment by mklemm** [comment]
Because the plugin doesn't support JAXB 2 anymore, the "2" has been removed from the artifactId. It's called:
`net.codesup.util:jaxb-rich-contract-plugin:4.2.0.0` now...
